// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOIJCtevYnSJTPLeWpkPDYUOqxovcux-s',
    appId: '1:879462826964:web:fd97add2db0c8d1f724c41',
    messagingSenderId: '879462826964',
    projectId: 'finzen-53ab0',
    authDomain: 'finzen-53ab0.firebaseapp.com',
    storageBucket: 'finzen-53ab0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Uqw8X0UVpNUzKNU_9S6-84kjf2wr6aQ',
    appId: '1:879462826964:android:086537824ff16b37724c41',
    messagingSenderId: '879462826964',
    projectId: 'finzen-53ab0',
    storageBucket: 'finzen-53ab0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc2BJeBsCAdpspr0q21yp9_VEfi4Zy6iE',
    appId: '1:879462826964:ios:a00e710ba6736636724c41',
    messagingSenderId: '879462826964',
    projectId: 'finzen-53ab0',
    storageBucket: 'finzen-53ab0.firebasestorage.app',
    iosBundleId: 'com.example.finzen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc2BJeBsCAdpspr0q21yp9_VEfi4Zy6iE',
    appId: '1:879462826964:ios:a00e710ba6736636724c41',
    messagingSenderId: '879462826964',
    projectId: 'finzen-53ab0',
    storageBucket: 'finzen-53ab0.firebasestorage.app',
    iosBundleId: 'com.example.finzen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOIJCtevYnSJTPLeWpkPDYUOqxovcux-s',
    appId: '1:879462826964:web:b15c180d69696aa5724c41',
    messagingSenderId: '879462826964',
    projectId: 'finzen-53ab0',
    authDomain: 'finzen-53ab0.firebaseapp.com',
    storageBucket: 'finzen-53ab0.firebasestorage.app',
  );
}
